<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
<ul id="menu" class="page-sidebar-menu">
    {{-- <li {!! (Request::is('backend') ? 'class="active"' : '') !!}>
        <a href="{{ route('backend') }}">
            <i class="livicon" data-name="home" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard</span>
        </a>
    </li> --}}

    <li {!! (Request::is('backend/users/*') || Request::is('backend/user/all') || Request::is('user') ||  Request::is('deleted_user') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="user" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">จัดการสมาชิก</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('backend/users/*') ? 'class="active" ' : '') !!}>
                <a href="{{ url('backend/users/index') }}">
                    <i class="fa fa-angle-double-right"></i>
                    สมาชิก
                </a>
            </li>
        </ul>
    </li>

    <li {!! (Request::is('backend') || Request::is('backend/classroom') || Request::is('backend/classroom/*') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="notebook" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">จัดการห้องประชุม</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('backend/classroom') ? 'class="active" ' : '') !!}>
                <a href="{{ URL::to('backend/classroom') }}">
                    <i class="fa fa-angle-double-right"></i>
                    ห้องประชุม
                </a>
            </li>
        </ul>
    </li>

    <li {!! (Request::is('backend/courses') || Request::is('backend/courses/*') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="notebook" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">จัดการหัวข้อประชุม</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('backend/courses') || Request::is('backend/courses/*') ? 'class="active" ' : '') !!}>
                <a href="{{ URL::to('backend/courses') }}">
                    <i class="fa fa-angle-double-right"></i>
                    หัวข้อประชุม
                </a>
            </li>
        </ul>
    </li>


    <!-- Menus generated by CRUD generator -->
    @include('backend/layouts/menu')
</ul>
</body>
